version: "3.4"

services:
  apimocksailpoint03:
    image: api_sailpoint_mock/afernandojr:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    volumes:
      - data:/data

volumes:
  data:
